DEFAULT:
  seed: 0
  savedir: ./results
  exp_name: 'Baseline'

DATASET:
  datadir: ../Data
  batch_size: 32
  test_batch_size: 32
  num_workers: 8
  dataset_name: MVTecLoco  # [AnomalyDataset,MVTecAD]
  aug_info: 
    - Resize
  class_name: juice_bottle
  img_size: 224
  params:
    anomaly_ratio: 0.2
    baseline: false

OPTIMIZER:
  opt_name: Adam
  lr: 0.005
  params:
    betas: 
    - 0.5
    - 0.999

TRAIN:
  epochs: 1
  grad_accum_steps: 1
  mixed_precision: 'fp16'
  log_interval: 1
  wandb:
    use: false
    project_name: ProxyCore
    
SCHEDULER: 
  name: null
  params: null
  