MODEL:
  method: CoreInit
  backbone: wide_resnet50_2
  params:
    input_shape:
      - 3 
      - 224
      - 224
    faiss_on_gpu: True
    faiss_num_workers: 4
    weight_method: identity # identity lof nearest gaussian
    threshold: quant_0.15
    sampling_ratio: 0.1
    pslabel_sampling_ratio: 0.25
    n_input_feat: 1024
    n_hidden_feat: 4096
    n_projection_feat: 1024
    temperature: 0.05
    loss_fn: focalloss #CrossEntropy focalloss



OPTIMIZER:
  opt_name: AdamP
  lr: 1e-5
  params:
    weight_decay: 1e-2

# SCHEDULER: 
#   name: CosineAnnealingLR
#   params: 
#     T_max: 100
#     eta_min: 1e-4

SCHEDULER: 
  name: null
  params: null
    
DATASET:
  embed_augemtation: True
  pseudo_label: normalize_coreset      # coreset normalize_coreset
  aug_info: 
    - PatchCore

TRAIN:
  epochs: 200
  log_interval: 10