OPTIMIZER:
  opt_name: Adam
  lr: 1e-3
  params:
    weight_decay: 1e-5

TRAIN:
  epochs: 200
  mixed_precision: 'no'
  


SCHEDULER: 
  name: CosineAnnealingLR
  params:
    T_max: 200  

MODEL:
  method: FastFlow
  backbone: wide_resnet50_2
  params:
    input_size: 
      - 224
      - 224
    flow_steps: 8