MODEL:
  method: ProxyCoreBase
  backbone: wide_resnet50_2
  params:
    input_shape:
      - 3 
      - 224
      - 224
    faiss_on_gpu: True
    faiss_num_workers: 4
    weight_method: identity # identity lof nearest gaussian
    threshold: quant_0.15
    sampling_ratio: 0.1
    n_input_feat: 1024
    n_hidden_feat: 4096
    n_projection_feat: 1024


OPTIMIZER:
  opt_name: AdamP
  lr: 1e-5
  params:
    weight_decay: 1e-2    

SCHEDULER: 
  name: null
  params: null

DATASET:
  aug_info: 
    - PatchCore
  params:
    baseline: True

TRAIN:
  epochs: 200
  log_interval: 10